### ISSUE TITLE
ModuleNotFoundError: No module named 'custom_backward_cpp'

### ISSUE THREAD

**Issue by jayurbain** [uber-research/GTN#1]
Environment:
MacOS 10.13.6
Installed pytorch==1.2, mpi4py, fire with conda. horovod with pip

Error: 
$ python train_cgtn.py .
Traceback (most recent call last):
  File "train_cgtn.py", line 24, in <module>
    from models import Classifier, Generator, Encoder, sample_model
  File "/Users/jayurbain/Dropbox/GTN/models.py", line 479, in <module>
    from exconv import ExConv2d
  File "/Users/jayurbain/Dropbox/GTN/exconv.py", line 16, in <module>
    import custom_backward_cpp
ModuleNotFoundError: No module named 'custom_backward_cpp'

Any direction would be appreciated.
Thanks,
Jay

**Comment by public-daniel** [comment]
You just need to run
```bash
python setup.py install
```
Checkout this guide from PyTorch for some additional details: https://brsoff.github.io/tutorials/advanced/cpp_extension.html
